version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    container_name: auth-nginx
    depends_on:
      - php-fpm
    restart: always
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
    restart: always
    container_name: auth-php-fpm
    depends_on:
      - postgres

  postgres:
    container_name: auth-postgres
    image: postgres:12
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
    environment:
        POSTGRES_DB: auth_db
        POSTGRES_USER: auth_user
        POSTGRES_PASSWORD: secret
    ports:
        - "15432:5432"
